espn_ffb/app.py
from espn_ffb import util
from espn_ffb.db.database import db
from espn_ffb.db.model.champions import Champions
from espn_ffb.db.model.matchups import Matchups
from espn_ffb.db.model.owners import Owners
from espn_ffb.db.model.records import Records
from espn_ffb.db.model.sackos import Sackos
from espn_ffb.db.model.teams import Teams
from espn_ffb.db.query import Query
from espn_ffb.views.awards import awards
from espn_ffb.views.champions import champions
from espn_ffb.views.h2h_records import h2h_records
from espn_ffb.views.matchup_history import matchup_history
from espn_ffb.views.playoffs import playoffs
from espn_ffb.views.recap import recap
from espn_ffb.views.standings import standings
from flask import Flask, redirect
import logging
import sys

LOG_FORMAT = "%(asctime)s %(levelname)s %(pathname)s %(lineno)d: %(message)s"

app = Flask(__name__)
app.config.from_object(util.get_config())
app.register_blueprint(awards)
app.register_blueprint(champions)
app.register_blueprint(h2h_records)
app.register_blueprint(matchup_history)
app.register_blueprint(playoffs)
app.register_blueprint(recap)
app.register_blueprint(standings)
app.static_folder = "web/static"
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SQLALCHEMY_DATABASE_URI'] = app.config.get("DB_URI")
db.init_app(app)
query = Query(db)
app.config['QUERY'] = query


@app.template_filter()
def number_format(value):
    return "{:,}".format(value)


@app.before_first_request
def setup_logging():
    if not app.debug:
        formatter = logging.Formatter(LOG_FORMAT)
        handler = logging.StreamHandler(sys.stdout)
        handler.setFormatter(formatter)
        app.logger.addHandler(handler)
        app.logger.setLevel(logging.INFO)


@app.route('/', methods=['GET'])
def show_index():
    return redirect("/awards", code=302)


if __name__ == "__main__":
    app.run(host='0.0.0.0')

espn_ffb/views/awards.py
from flask import Blueprint, render_template

awards = Blueprint("awards", __name__, template_folder="templates")


@awards.route('/awards', methods=['GET'])
def show():
    return render_template("awards.html", title='Settings')

espn_ffb/views/champions.py
from collections import namedtuple
from flask import Blueprint, current_app, render_template

champions = Blueprint("champions", __name__, template_folder="templates")
TABLE_HEADERS = ['Year', 'Champion']
COLUMN_NAMES = ['year', 'champion']
Record = namedtuple('Champions', COLUMN_NAMES)


def get_records(query):
    records = list()
    champions, owners = zip(*query.get_champions())

    for c, o in zip(champions, owners):
        records.append(Record(year=c.year, champion=o.first_name + " " + o.last_name))

    return records


@champions.route('/champions', methods=['GET'])
def show():
    query = current_app.config.get("QUERY")
    records = get_records(query)

    return render_template('champions.html', title='Champions', table_headers=TABLE_HEADERS,
                           column_names=COLUMN_NAMES, records=records)

espn_ffb/views/h2h_records.py
from flask import Blueprint, current_app, render_template, request
from espn_ffb import util

h2h_records = Blueprint("h2h_records", __name__, template_folder="templates")
TABLE_HEADERS = ['Opponent', 'Wins', 'Losses']
COLUMN_NAMES = ['opponent_name', 'wins', 'losses']


@h2h_records.route('/h2h-records', methods=['GET'])
def show():
    query = current_app.config.get("QUERY")

    matchup_type = request.args.get('matchup_type', default=util.REGULAR_SEASON)
    owner_id = request.args.get('owner_id', type=str)

    owners = query.get_owners()
    is_playoffs = util.get_is_playoffs(matchup_type)

    if not owner_id:
        owner_id = owners[0].id

    records = query.get_h2h_records(owner_id=owner_id, is_playoffs=is_playoffs)
    return render_template("h2h-records.html", title='H2H Records', table_headers=TABLE_HEADERS,
                           column_names=COLUMN_NAMES, matchup_type=matchup_type, owners=owners, selected_owner=owner_id,
                           records=records)

espn_ffb/views/matchup_history.py
from flask import Blueprint, current_app, render_template, request
from espn_ffb import util

matchup_history = Blueprint("matchup_history", __name__, template_folder="templates")
TABLE_HEADERS = ["Year", "Matchup ID", "Team", "Opponent Score", "Result"]
COLUMN_NAMES = ["year", "matchup_id", "team_score", "opponent_team_score", "is_win"]


@matchup_history.route('/matchup-history', methods=['GET'])
def show():
    query = current_app.config.get("QUERY")

    matchup_type = request.args.get('matchup_type', default=util.REGULAR_SEASON)
    owner_id = request.args.get('owner_id', type=str)
    opponent_owner_id = request.args.get('opponent_owner_id', type=str)

    owners = query.get_owners()
    is_playoffs = util.get_is_playoffs(matchup_type)

    if not owner_id:
        owner_id = owners[0].id
        opponent_owner_id = owners[1].id

    records = query.get_matchup_history(owner_id=owner_id, opponent_owner_id=opponent_owner_id, is_playoffs=is_playoffs)
    return render_template('matchup-history.html', title='Matchup History', table_headers=TABLE_HEADERS,
                           column_names=COLUMN_NAMES, matchup_type=matchup_type, owners=owners, selected_owner=owner_id,
                           selected_opponent=opponent_owner_id, records=records)

espn_ffb/views/playoffs.py
from flask import Blueprint, render_template

playoffs = Blueprint("playoffs", __name__, template_folder="templates")


@playoffs.route('/playoffs/<int:year>', methods=['GET'])
def show(year):
    # noinspection PyUnresolvedReferences
    return render_template(f"playoffs/{year}.html", title='{year} Playoffs')

espn_ffb/views/recap.py
from flask import Blueprint, current_app, render_template
from espn_ffb import util

recap = Blueprint("recap", __name__, template_folder="templates")


@recap.route('/recap/<int:year>/<int:week>', methods=['GET'])
def show(year, week):
    query = current_app.config.get("QUERY")

    team_ids = set(query.get_distinct_matchup_team_ids(year)[week])
    matchups = [m for m in query.get_matchups(year) if m.matchup_id == week and m.team_id in team_ids]
    matchups = sorted(matchups, key=lambda m: m.team_id)
    win_streaks = query.get_win_streak_by_year(matchups, year, week)
    team_id_to_record = query.get_team_id_to_record(year, week)
    team_id_to_team_name = query.get_team_id_to_team_name(year)
    h2h_records = query.get_h2h_record_current(matchups, year, week)

    recaps = list()
    for m, ws, h2h_record in zip(matchups, win_streaks, h2h_records):
        streak_owner = team_id_to_team_name.get(ws.streak_owner)

        recaps.append(
            util.Recap(
                team=team_id_to_team_name[m.team_id],
                team_record=team_id_to_record[m.team_id],
                opponent=team_id_to_team_name[m.opponent_team_id],
                opponent_record=team_id_to_record[m.opponent_team_id],
                streak=ws.streak,
                streak_owner=streak_owner,
                h2h_record=h2h_record,
                body=f"recap/{year}/{week}/{m.team_id}.html"
            )
        )
    return render_template("recap.html", title='Weekly Recap', recaps=recaps)

espn_ffb/views/standings.py
from flask import Blueprint, current_app, render_template

standings = Blueprint("standings", __name__, template_folder="templates")
TABLE_HEADERS = ["Name", "Wins", "Losses", "Win Percentage", "Points For", "Points Against", "Average Points For",
                 "Average Points Against", "Championships", "Sackos"]
COLUMN_NAMES = ["owner_id", "wins", "losses", "win_percentage", "points_for", "points_against", "avg_points_for",
                "avg_points_against", "championships", "sackos"]


def get_owner_id_to_name(query):
    return {o.id: o.first_name + " " + o.last_name for o in query.get_owners()}


@standings.route('/standings/<string:year>', methods=['GET'])
def show(year: str):
    # return "<h1 style='color:blue'>Hello There!</h1>" + str(sys.argv[1])
    query = current_app.config.get("QUERY")

    owner_id_to_name = get_owner_id_to_name(query)
    sacko = query.get_sacko_current()

    if year == "overall":
        records = query.get_standings_overall()
    else:
        records = query.get_standings(year=int(year))

    return render_template('standings.html', title='Standings', table_headers=TABLE_HEADERS,
                           column_names=COLUMN_NAMES, records=records, sacko=sacko,
                           owner_id_to_name=owner_id_to_name)

espn_ffb/templates/awards.html
{%- extends "base.html" -%}
{% block nav_awards %}active{% endblock %}
{%- block content %}
  <br>
  <b>Weekly Payouts ($10)</b>
  <div class="stats-table">
    <table>
      <tr>
        <th>Week</th>
        <th>Position</th>
        <th>Criteria</th>
        <th>Winner</th>
        <th>Player</th>
        <th>Winning Stat</th>
      </tr>
      <tr>
        <td>1</td>
        <td>QB</td>
        <td>Passing yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>2</td>
        <td>RB</td>
        <td>Rushing yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>3</td>
        <td>WR / TE</td>
        <td>Receiving yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>4</td>
        <td>QB</td>
        <td>Passing yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>5</td>
        <td>RB</td>
        <td>Rushing yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>6</td>
        <td>WR / TE</td>
        <td>Receiving yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>7</td>
        <td>QB</td>
        <td>Passing yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>8</td>
        <td>RB</td>
        <td>Rushing yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>9</td>
        <td>WR / TE</td>
        <td>Receiving yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>10</td>
        <td>QB</td>
        <td>Passing yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>11</td>
        <td>RB</td>
        <td>Rushing yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>12</td>
        <td>WR / TE</td>
        <td>Receiving yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>13</td>
        <td>QB</td>
        <td>Passing yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>14</td>
        <td>RB</td>
        <td>Rushing yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>15</td>
        <td>WR / TE</td>
        <td>Receiving yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>16</td>
        <td>QB</td>
        <td>Passing yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>17</td>
        <td>RB</td>
        <td>Rushing yards</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </table>
  </div>
  <br>
  <b>Season Payouts ($30)</b>
  <div class="stats-table">
    <table>
      <tr>
        <th>Criteria</th>
        <th>Winner</th>
        <th>Player</th>
        <th>Winning Stat</th>
        <th>Week</th>
      </tr>
      <tr>
        <td>Longest passing TD</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>Longest rushing TD</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>Longest receiving TD</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </table>
  </div>
{%- endblock -%}

espn_ffb/templates/base.html
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/table.css') }}"/>
    {%- block recap_css %}{% endblock %}
    <script src="{{ url_for('static', filename='js/sort.js') }}"></script>
    <script src="{{ url_for('static', filename='js/navbar.js') }}"></script>
  </head>
  <div class="topnav" id="myTopnav">
    <a href="{{ url_for('awards.show') }}" class="{% block nav_awards %}{% endblock %}">Awards</a>
    <div class="dropdown {% block nav_standings %}{% endblock %}">
      <button class="dropbtn">Standings<i class="fa fa-caret-down"></i></button>
      <div class="dropdown-content">
        <a href="{{ url_for('standings.show', year='overall') }}">Overall</a>
        <a href="{{ url_for('standings.show', year=2019) }}">2019</a>
      </div>
    </div>
    <a href="{{ url_for('h2h_records.show') }}" class="{% block nav_h2h %}{% endblock %}">H2H Records</a>
    <a href="{{ url_for('matchup_history.show') }}" class="{% block nav_matchups %}{% endblock %}">Matchup History</a>
    <div class="dropdown {% block nav_recap %}{% endblock %}">
      <button class="dropbtn">Recap<i class="fa fa-caret-down"></i></button>
      <div class="dropdown-content">
        <a href="{{ url_for('recap.show', year=2018, week=2) }}">2018, Week 2</a>
      </div>
    </div>
    <a href="{{ url_for('champions.show') }}" class="{% block nav_champions %}{% endblock %}">Champions</a>
    <div class="dropdown {% block nav_playoffs %}{% endblock %}">
      <button class="dropbtn">Playoffs<i class="fa fa-caret-down"></i></button>
      <div class="dropdown-content">
        <a href="{{ url_for('playoffs.show', year=2018) }}">2018</a>
      </div>
    </div>
    <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
  </div>
  {%- block content %}{% endblock %}
</html>

espn_ffb/templates/champions.html
{%- extends "base.html" -%}
{% block nav_champions %}active{% endblock %}
{%- block content -%}
  {%- if records|length > 0 %}
  <div class="stats-table">
    <table>
      <tr>
        {%- for th in table_headers %}
        <th>{{ th }}</th>
        {%- endfor %}
      </tr>
      {%- for r in records %}
      <tr>
        {%- for cn in column_names %}
        <td>{{ r[cn] }}</td>
        {%- endfor %}
      </tr>
      {%- endfor %}
    </table>
  </div>
  {%- endif %}
{%- endblock -%}

espn_ffb/templates/h2h-records.html
{%- extends "base.html" -%}
{% block nav_h2h %}active{% endblock %}
{%- block content %}
  <form action="{{ url_for('h2h_records.show') }}" method="get">
    <label>
      <select name="owner_id" onchange="this.form.submit()">
      {%- for o in owners %}
        <option value="{{ o.id }}" {%- if o.id == selected_owner %} selected {% endif %}>{{o.first_name + " " + o.last_name }}</option>
      {%- endfor %}
      </select>
    </label>
    <label><input type="radio" name="matchup_type" value="regular" onclick="this.form.submit()" {%- if matchup_type == "regular" %} checked {% endif %}>Regular Season</label>
    <label><input type="radio" name="matchup_type" value="playoffs" onclick="this.form.submit()"{%- if matchup_type == "playoffs" %} checked {% endif %}>Playoffs</label>
  </form>
  {%- if records|length > 0 %}
  <div class="stats-table">
    <table>
      <tr>
        {%- for th in table_headers %}
        <th>{{ th }}</th>
        {%- endfor %}
      </tr>
      {%- for r in records %}
      <tr>
        {%- for cn in column_names %}
        <td>{{ r[cn] }}</td>
        {%- endfor %}
      </tr>
      {%- endfor %}
    </table>
  </div>
  {%- endif %}
{%- endblock -%}

espn_ffb/templates/matchup-history.html
{%- extends "base.html" -%}
{% block nav_matchups %}active{% endblock %}
{%- block content -%}
  <form action="{{ url_for('matchup_history.show') }}" method="get">
    <label>
      Owner:
      <select name="owner_id" onchange="this.form.submit()">
        {%- for o in owners %}
          {%- if o.owner_id != selected_opponent %}
        <option value="{{ o.id }}" {%- if o.id == selected_owner %} selected {% endif %}>{{ o.first_name + " " + o.last_name }}</option>
          {%- endif -%}
        {%- endfor %}
      </select>
    </label>
    <br><br>
    <label>
      Opponent:
      <select name="opponent_owner_id" onchange="this.form.submit()">
        {%- for o in owners %}
          {%- if o.owner_id != selected_owner %}
        <option value="{{ o.id }}" {%- if o.id == selected_opponent %} selected {% endif %}>{{ o.first_name + " " + o.last_name }}</option>
          {%- endif -%}
        {%- endfor %}
      </select>
    </label>
    <label><input type="radio" name="matchup_type" value="regular" onclick="this.form.submit()" {%- if matchup_type == "regular" %} checked {% endif %}>Regular Season</label>
    <label><input type="radio" name="matchup_type" value="playoffs" onclick="this.form.submit()"{%- if matchup_type == "playoffs" %} checked {% endif %}>Playoffs</label>
  </form>
  {%- if records|length > 0 %}
  <div class="stats-table">
    <table>
      <tr>
        {%- for th in table_headers %}
        <th>{{ th }}</th>
        {%- endfor %}
      </tr>
      {%- for r in records %}
      <tr>
        {%- for cn in column_names %}
        {%- if cn == "is_win" %}
          {%- if r[cn] %}
        <td>W</td>
          {%- else %}
         <td>L</td>
          {%- endif %}
        {%- else %}
        <td>{{ r[cn] }}</td>
        {%- endif %}
        {%- endfor %}
      </tr>
      {%- endfor %}
    </table>
  </div>
  {%- endif %}
{%- endblock -%}

espn_ffb/templates/playoffs/2018.html
{%- extends "base.html" -%}
{% block nav_playoffs %}active{% endblock %}
{%- block content %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bracket.css') }}"/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Holtwood+One+SC' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script|Herr+Von+Muellerhoff' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Istok+Web|Roboto+Condensed:700' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <header class="hero">
      <div class="hero-wrap">
        <p class="intro" id="intro">The League</p>
        <h1 id="headline">Year Nine</h1>
        <p class="year"><i class="fa fa-star"></i> 2018 <i class="fa fa-star"></i></p>
      </div>
    </header>
    <section id="bracket">
      <div class="container">
        <div class="round round-one">
          <div class="round-details">Wildcard<br/></div>
          <ul class="matchup">
            <li class="team team-top">3&nbsp;&nbsp;team one<span class="score">104.4</span></li>
            <li class="team team-bottom">6&nbsp;&nbsp;team two<span class="score">164</span></li>
          </ul>
          <ul class="matchup">
            <li class="team team-top">4&nbsp;&nbsp;team three<span class="score">151.6</span></li>
            <li class="team team-bottom">5&nbsp;&nbsp;team four<span class="score">95.4</span></li>
          </ul>
        </div>
        <div class="round round-one">
          <div class="round-details">Conference Finals<br/></div>
          <ul class="matchup">
            <li class="team team-top">1&nbsp;&nbsp;team five<span class="score">138.2</span></li>
            <li class="team team-bottom">4&nbsp;&nbsp;team three<span class="score">88</span></li>
          </ul>
          <ul class="matchup">
            <li class="team team-top">2&nbsp;&nbsp;team six<span class="score">129.4</span></li>
            <li class="team team-bottom">6&nbsp;&nbsp;team two<span class="score">71.2</span></li>
          </ul>
        </div>
        <div class="round round-two">
          <div class="round-details">Money League Bowl<br/></div>
          <ul class="matchup">
            <li class="team team-top">1&nbsp;&nbsp;team five<span class="score">114.1</span></li>
            <li class="team team-bottom">2&nbsp;&nbsp;team six<span class="score">182.4</span></li>
          </ul>
        </div>
        <div class="round round-two current">
          <div class="round-details">Champion<br/></div>
          <ul class="matchup">
            <li class="team team-top">2&nbsp;&nbsp;team six</li>
            <li class="team team-bottom"></li>
          </ul>
        </div>
        <div class="image"><img height=120 src="{{ url_for('static', filename='images/trophy.png') }}"/></div>
      </div>
      <br><br>
      <div class="container">
        <div class="round round-one">
          <div class="round-details">Wild Sacko<br/></div>
          <ul class="matchup">
            <li class="team team-top">7&nbsp;&nbsp;team seven<span class="score">109.7</span></li>
            <li class="team team-bottom">10&nbsp;team eight<span class="score">98</span></li>
          </ul>
          <ul class="matchup">
            <li class="team team-top">8&nbsp;&nbsp;team nine<span class="score">98.5</span></li>
            <li class="team team-bottom">9&nbsp;&nbsp;team twelve<span class="score">148.7</span></li>
          </ul>
        </div>
        <div class="round round-one">
          <div class="round-details">Conference Sackos<br/></div>
          <ul class="matchup">
            <li class="team team-top">8&nbsp;&nbsp;team nine<span class="score">94.3</span></li>
            <li class="team team-bottom">12&nbsp;team ten<span class="score">116.5</span></li>
          </ul>
          <ul class="matchup">
            <li class="team team-top">10&nbsp;team eight<span class="score">70.3</span></li>
            <li class="team team-bottom">11&nbsp;team eleven<span class="score">107.6</span></li>
          </ul>
        </div>
        <div class="round round-two">
          <div class="round-details">Sacko Bowl<br/></div>
          <ul class="matchup">
            <li class="team team-top">8&nbsp;&nbsp;team nine<span class="score">135.6</span></li>
            <li class="team team-bottom">10&nbsp;team eight<span class="score">151.3</span></li>
          </ul>
        </div>
        <div class="round round-two current">
          <div class="round-details">Sacko<br/></div>
          <ul class="matchup">
            <li class="team team-top">8&nbsp;&nbsp;team nine</li>
            <li class="team team-bottom"></li>
          </ul>
        </div>
        <div class="image"><img height=80 src="{{ url_for('static', filename='images/sacko-current.png') }}"/></div>
      </div>
    </section>
  </body>
{%- endblock -%}

espn_ffb/templates/recap.html
{%- extends "base.html" %}
{% block recap_css %}<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/recap.css') }}"/>{% endblock %}
{% block nav_recap %}active{% endblock %}
{%- block content %}
  <div>
    <div class="column">
      {%- for r in recaps %}
      <div class="card">
        <h2>
          {{ r.team }} ({{ r.team_record.wins }}-{{ r.team_record.losses }})
          <br>
          vs.
          <br>
          {{ r.opponent }} ({{ r.opponent_record.wins }}-{{ r.opponent_record.losses }})
        </h2>
        <h5>All-time: ({{ r.h2h_record.wins }}-{{ r.h2h_record.losses }}), Win streak: {{ r.streak }} ({{ r.streak_owner }})</h5>
        {%- include r.body %}
      </div>
      {%- endfor %}
    </div>
  </div>
{%- endblock %}

espn_ffb/templates/recap/2018/2/1.html
        {#- {{ r.team }} = "team 1" -#}
        {#- {{ r.opponent }} = "team 2" #}
        <img class="img" src="{{ url_for('static', filename='images/recap/2018/2/aj-green.jpg') }}">
        <p>If A.J. Green's 3td (<a href="https://www.clippituser.tv/c/bnqeyy">1</a>-<a href="https://www.clippituser.tv/c/wxedpz">2</a>-<a href="https://www.clippituser.tv/c/qvbamy">3</a>) performance in the 1st half of Thursday night's game didn't discourage
          {{ r.opponent }} from showing up, surely he had to question his ability to pull off a comeback after Ben Roethlisberger dropped 41 points on 39-60 with 452yd and 4td including one rushing.
          As <a href="https://www.clippituser.tv/c/rybwwa">Big Ben dived into the endzone without consent</a>, so too did {{ r.opponent }}'s chance of a W.
          <br><br>
          James Conner continues to produce for {{ r.team }} including <a href="https://streamable.com/mscdd">this beauty of a grab</a>.
          Meanwhile <a href="https://twitter.com/LeVeonBell/status/1038894196298539010">Le'veon Bell exercises his twitter fingers</a> from his couch.
          <br><br>
          The return of Mark Ingram II comes in two weeks and {{ r.team }} must be ecstatic about that as he stays undefeated heading into week 3 2-0. Meanwhile, {{ r.opponent }} drops to 1-1 and hopes to put this abysmal performance behind him.
        </p>

espn_ffb/templates/recap/2018/2/2.html
        {#- {{ r.team }} = "team 1" -#}
        {#- {{ r.opponent }} = "team 2" #}
        <img class="img" src="{{ url_for('static', filename='images/recap/2018/2/breida.jpg') }}">
        <p>{{ r.opponent }} must be shaking his head as his team threw away a historic effort by Patrick Mahomes. Mahomes had not
          <a href="https://streamable.com/una04">1</a>, not <a href="https://streamable.com/v8to0">2</a>, not <a href="https://streamable.com/804cj">3</a>,
          not <a href="https://streamable.com/dj5r0">4</a>, not <a href="https://streamable.com/acbdb">5</a>, but <a href="https://streamable.com/s7tt7">6</a> touchdowns for the day, breaking the NFL records for most touchdown passes in the first two games of the season.
          Sadly, his effort was immediately nullified by Kirk "Kurt" Cousins who threw for 425yd and 4td.
          <br><br>
          Missing from action was {{ r.opponent }}' wide receiver corp as the Julio Jones and Keenan Allen duo checked in forgettable performances. On the other side of the coin, both Will Fuller V and Matt Breida had long touchdowns.
          Fuller hauled in this <a href="https://streamable.com/xnyy7">39yd td bomb</a> from Deshaun Watson and Breida ran for a <a href="https://streamable.com/qhilr">66yd td</a> behind the coattails of Pierre Garcon for the score.
          <br><br>
          Perhaps {{ r.opponent }}' biggest regret remained on the bench as his Bears D/ST would have made up the difference and given him the win. Both {{ r.opponent }} and {{ r.team }} walk away 1-1.
        </p>